export const metadata = {
  title: 'Electronics  Maya',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es-MX">
      <link rel="shortcut icon" href="https://web.opendrive.com/api/v1/download/file.json/MjdfMjA3ODAwMThfbzA5ajc?session_id=efca6f8acf26360a9c88260d05ae0096778a41cf8a6082ff0b5f424229e89988&inline=1&preview=1" />
      <body>{children}</body>
    </html>
  )
}
